feat: add route, GET method article-hot
Journey-bites/journey-bites-service pull request #11
Opened 2024-06-04 13:21 UTC by LTK228

新增熱門文章：
可以篩選數量 likes 數最多的文章，如果使用者有輸入參數

使用範例：
- `/api/v1/articles-hot`
  - 未提供參數，
- `/api/v1/articles-hot?count=5`
  - 有提供參數 `count`，會篩選出 likes 數

2024-06-04 13:22 UTC, ba1679 commented
some conflicts need to be fix

2024-06-04 13:36 UTC, LTK228 commented
resolved conflicts

2024-06-04 13:37 UTC, ba1679 requested changes

2024-06-04 13:37 UTC, ba1679 commented on .gitignore
> +pnpm-lock.yaml
[Required] `pnpm-lock.yaml` 跟 `package-lock.json` 一樣不應放在 .gitignore
https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

2024-06-04 13:37 UTC, ba1679 commented on prisma/schema.prisma
> +  creator      String // user.username // https://ithelp.ithome.com.tw/articles/10251700
[Suggested] 不必要的註解建議拿掉哦

2024-06-04 13:37 UTC, ba1679 commented on pnpm-lock.yaml
[Required] pnpm 用錯版本了

2024-06-04 13:37 UTC, ba1679 commented on src/services/articleHotServices.ts
> +import prisma from '@/db';
[Required] 既有的 service 用 db 當作命名，建議保持一致
```suggestion
import db from '@/db';
```

2024-06-04 13:37 UTC, ba1679 commented on src/routes/articleHot.ts
> +// import userController from '@/controllers/userController';
[Required] 不必要的註解需拿掉

2024-06-04 13:37 UTC, ba1679 commented on src/controllers/articleHotController.ts
[Suggested] 熱門文章為名詞，感覺用 hotArticles 比 articleHot 合適 (多處)

2024-06-04 13:37 UTC, ba1679 commented on src/controllers/articleHotController.ts
> +      const parmCount = req.query.count as string;
[Required] query 應該可以定義型別
https://stackoverflow.com/a/73089957/24814058

2024-06-04 13:42 UTC, ba1679 requested changes

2024-06-04 13:42 UTC, ba1679 commented on src/routes/index.ts
> +router.use('/articles-hot', authenticate, articleHotRouter);
[Required] 這隻 API 不需要 authenticate

2024-06-05 15:38 UTC, ba1679 reviewed
以上建議有問題可留言回覆討論～
(DB 操作的部分我還沒細看)

2024-06-05 15:38 UTC, ba1679 commented on prisma/schema.prisma
> +model StatusArticle {
[Suggested] ArticleStatus 可能比較好懂一點

2024-06-05 15:38 UTC, ba1679 commented on src/controllers/articleHotController.ts
> +const userController = {
[Required] 名稱忘了改

2024-06-05 15:38 UTC, ba1679 commented on src/controllers/articleHotController.ts
> +      const parmCount = req.query.count as string;
[Suggested] `parmCount` 這個命名可以再想一下

2024-06-10 02:37 UTC, LTK228 commented on src/services/articleHotServices.ts
> +      // status: true,
移除註解

2024-06-10 02:41 UTC, LTK228 commented
feat: add route, GET method hot-article

新增熱門文章：
可以篩選數量 likes 數最多的文章，如果使用者有輸入參數

使用範例：
- `/api/v1/hot-articles`
  - 未提供參數，
- `/api/v1/hot-articles?count=5`
  - 有提供參數 `count`，會篩選出 likes 數
  
程式功能
1. query 型別
  https://stackoverflow.com/a/73089957/24814058
2. pnpm-lock.yaml 跟 package-lock.json 一樣不應放在 .gitignore
  https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore
3. 熱門文章 API 不需要 authenticate
4. pnpm 版本升級至 9.0 以上

修改命名
1. 既有的 service 用 db 當作命名，建議保持一致
2. articleHot → hotArticles
3. StatusArticle → ArticleStatus

清除註解
1. 移除不必要的註解

2024-06-10 08:16 UTC, ba1679 approved these changes
有些套件在 pnpm-lock 看起來被升級了，不確定會不會影響到，另外有一個 error message 沒有改到，需改一下，其他 ok

2024-06-10 08:16 UTC, ba1679 commented on src/controllers/hotArticleController.ts
> +      throw new SystemException('Error while getting user info');
Error message 沒有改到，這樣未來 debug 會亂掉

2024-06-10 11:23 UTC, LTK228 reviewed
fix: Error message

2024-06-10 11:24 UTC, merged

2024-06-10 11:25 UTC, LTK228 commented on src/controllers/hotArticleController.ts
> +      throw new SystemException('Error while getting user info');
fix: Error message