feat/category api
Journey-bites/journey-bites-service pull request #20
Opened 2024-06-17 15:12 UTC by LTK228

2024-06-18 05:16 UTC, ba1679 requested changes

2024-06-18 05:16 UTC, ba1679 commented on src/services/categoryServices.ts
> +    return await db.categories.findMany();
前端不需要知道 createdAt & updatedAt，可以濾掉

2024-06-18 05:16 UTC, ba1679 commented on src/routes/category.ts
> +    }
creators -> categories

2024-06-18 05:16 UTC, ba1679 commented on src/routes/category.ts
> +      description: 'Creators',
Creators -> Categories

2024-06-18 05:16 UTC, ba1679 commented on src/services/categoryServices.ts
> +    return await db.categories.findMany();
如果裡面沒有 category 資料是否會出錯

2024-06-18 05:16 UTC, ba1679 commented on src/controllers/categoryController.ts
> +  getCategory: async (req: AddCategoryRequest, res: Response, next: NextFunction) => {
get method req type 錯了

2024-06-18 13:03 UTC, CoolizzLuo requested changes

2024-06-18 13:03 UTC, CoolizzLuo commented on src/controllers/categoryController.ts
> +        message: 'Categories fetched successfully',
用 `fetched` 好像不是很洽當

2024-06-18 13:03 UTC, CoolizzLuo commented on src/controllers/categoryController.ts
> +      next(new SystemException('Error while fetching categories'));
用 `fetching` 好像不是很洽當

2024-06-23 12:19 UTC, CoolizzLuo approved these changes
Some suggestions

2024-06-23 12:19 UTC, CoolizzLuo commented on src/services/categoryServices.ts
> +    }));
應該可以下一些 prisma 語法去篩選掉

2024-06-23 12:19 UTC, CoolizzLuo commented on src/routes/category.ts
> +                "updatedAt": "2024-06-17T18:28:45.135Z"
這兩個看起來不會給

2024-06-23 13:24 UTC, ba1679 approved these changes

2024-06-23 13:24 UTC, merged